In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler,LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('bank-full.csv',delimiter=';')
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

## EDA

In [3]:
df.shape

(45211, 17)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [5]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [6]:
df.duplicated().sum()

0

In [7]:
features = df.drop('y', axis=1)
features

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome  
0        unknown    5   may       261         1     -1         0  unknown  
1        unknown    5   may       151         1     -1         0  unknown  
2        unknown    5   may        76         1     -1         0  unknown  
3        unknown    5   may        92         1     -1         0  unknown  
4        unknown    5   may       198         1     -1         0  unknown  
...          ...  ...   ...       ...       ...    ...       ...      ...  
45206   cellular   17   nov       977         3     -1         0  unknown  
45207   cellular   17   nov       456         2     -1         0  unknown  
45208   cellular   17   nov      1127         5    184         3  success  
45209  telephone   17   nov       508         4     -1         0  unknown  
45210   cellular   17   nov       361         2    188        11    other  

[45211 rows x 16 columns]

In [8]:
target = df[['y']]
target

y
0       no
1       no
2       no
3       no
4       no
...    ...
45206  yes
45207  yes
45208  yes
45209   no
45210   no

[45211 rows x 1 columns]

## Converts the categorical features  into numerical features

In [9]:
features = pd.get_dummies(features)
features

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0       58     2143    5       261         1     -1         0           0   
1       44       29    5       151         1     -1         0           0   
2       33        2    5        76         1     -1         0           0   
3       47     1506    5        92         1     -1         0           0   
4       33        1    5       198         1     -1         0           0   
...    ...      ...  ...       ...       ...    ...       ...         ...   
45206   51      825   17       977         3     -1         0           0   
45207   71     1729   17       456         2     -1         0           0   
45208   72     5715   17      1127         5    184         3           0   
45209   57      668   17       508         4     -1         0           0   
45210   37     2971   17       361         2    188        11           0   

       job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  \
0                    0                 0  ...          0          0   
1                    0                 0  ...          0          0   
2                    0                 1  ...          0          0   
3                    1                 0  ...          0          0   
4                    0                 0  ...          0          0   
...                ...               ...  ...        ...        ...   
45206                0                 0  ...          0          0   
45207                0                 0  ...          0          0   
45208                0                 0  ...          0          0   
45209                1                 0  ...          0          0   
45210                0                 1  ...          0          0   

       month_may  month_nov  month_oct  month_sep  poutcome_failure  \
0              1          0          0          0                 0   
1              1          0          0          0                 0   
2              1          0          0          0                 0   
3              1          0          0          0                 0   
4              1          0          0          0                 0   
...          ...        ...        ...        ...               ...   
45206          0          1          0          0                 0   
45207          0          1          0          0                 0   
45208          0          1          0          0                 0   
45209          0          1          0          0                 0   
45210          0          1          0          0                 0   

       poutcome_other  poutcome_success  poutcome_unknown  
0                   0                 0                 1  
1                   0                 0                 1  
2                   0                 0                 1  
3                   0                 0                 1  
4                   0                 0                 1  
...               ...               ...               ...  
45206               0                 0                 1  
45207               0                 0                 1  
45208               0                 1                 0  
45209               0                 0                 1  
45210               1                 0                 0  

[45211 rows x 51 columns]

In [ ]:
sns.displot(features)

## Label Encoder

In [11]:
le = LabelEncoder()
target = le.fit_transform(target)

## Spliting into training & testing data

In [12]:
x_train,x_test,y_train,y_test =train_test_split(features,target,train_size=0.8,random_state=100)

In [23]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(36168, 51)
(36168,)
(9043, 51)
(9043,)


## Logistic Regression

In [24]:
logi_model =LogisticRegression()

In [25]:
logi_model.fit(x_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
y_pred = logi_model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
accuracy_score(y_test,y_pred)

0.8906336392790003

In [28]:
confusion_matrix(y_test,y_pred)

array([[7829,  175],
       [ 814,  225]], dtype=int64)

In [29]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94      8004
           1       0.56      0.22      0.31      1039

    accuracy                           0.89      9043
   macro avg       0.73      0.60      0.63      9043
weighted avg       0.87      0.89      0.87      9043



In [30]:
y_test

array([0, 0, 0, ..., 0, 0, 0])