In [5]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import norm

In [10]:
# Avg. weight of Adult in Mexico with 94% CI
conf_94 = stats.t.interval(confidence=0.94,df=1999,loc=200,scale=30/np.sqrt(2000))
np.round(conf_94,2)

array([198.74, 201.26])

In [13]:
# Avg. weight of Adult in mexico with 96% CI
conf_96= stats.t.interval(confidence=0.96,df=1999,loc=200,scale=30/np.sqrt(2000))
np.round(conf_96,2)

array([198.62, 201.38])

In [15]:
# Avg. weight of Adult in mexico with 98% CI
conf_98= stats.t.interval(confidence=0.98,df=1999,loc=200,scale=30/np.sqrt(2000))
np.round(conf_98,2)

array([198.44, 201.56])